import { AuthProvider } from "./Providers";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gym buddy",
  description: "Generated by christy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-h-screen`}>
        <AuthProvider>{children} </AuthProvider>
      </body>
    </html>
  );
}
